name: password_manager_server
description: A Dart server for managing passwords API requests.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_cors_headers: ^0.1.5
  postgres: ^3.5.6
  dotenv: ^4.2.0  # Для загрузки переменных окружения
  hashing_utility_package:
    path: ../common/utility
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1