name: password_manager_server
description: A Dart server for managing passwords API requests.

environment:
  #sdk: ^3.5.3
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  #flutter:
  #sdk: flutter
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_cors_headers: ^0.1.5
  postgres: ^3.4.0
  dotenv: ^4.2.0  # Для загрузки переменных окружения
  hashing_utility_package:
    path: ../common/utility
  logger: ^1.3.1

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
