@startuml
actor Клиент
entity Сервер
database БД

Клиент -> Сервер: Отправляет запрос\nна регистрацию
Сервер -> Сервер: Шифрует пароль
Сервер -> Сервер: Генерирует aes_key на основе secret_phrase
Сервер -> БД: 'Отправляет данные(\naccount_login,\nemail_address,\npassword,\n aes_key,\n user_name,\n user_phone,\n user_description)
БД -> БД: Сохраняет данные в базе данных
БД -> Сервер: Возвращает данные (account_id, user_id, email_id)
Сервер -> Клиент: Отправляет ответ\n с JWT токеном и данными регистрации

@enduml
