@startuml

autonumber
actor Клиент
entity Сервер
database БД

Клиент -> Сервер: Request (Регистрация):\n- логинАккаунта,\n- пароль,\n- почта,\n- парольПочты,\n- фраза
Сервер -> Сервер: Шифрует пароль
Сервер -> Сервер: Формирует токен
Сервер -> Сервер: Формирует aes_key
Сервер -> БД: Request:\n- логинАккаунта,\n- имяПользователя, \n- никнейм,\n- зашифрованныйПароль,\n- почта,\n- зашифрованныйПарольПочты,\n- aes_key
БД -> БД: Сохраняет логинАккаунта в таблицу accounts
БД -> БД: Сохраняет имяПользователя в таблицу users
БД -> БД: Сохраняет никнейм в таблицу nicknames
БД -> БД: Сохраняет зашифрованныйПароль в таблицу accounts
БД -> БД: Сохраняет почту в таблицу emails
БД -> БД: Сохраняет зашифрованныйПарольПочты в таблицу emails
БД -> Сервер: Response:\n- account_id,\n- user_id,\n- email_id\n- aes_key
Сервер -> Клиент: токен & aes_key
Клиент -> Клиент: Сохраняет в SecureStorage aes_key
note right: Какое то время спустя: Срок жизни токена истек
Клиент -> Сервер: aes_key + пароль
note left: Хочет обновить токен
Сервер -> Сервер: Обновляет токен
Сервер -> Клиент: Отдает новый токен & aes_key

@enduml