@startuml

autonumber
actor Клиент
entity Сервер

Клиент -> Сервер: пароль + фраза + соль
Сервер -> Сервер: Шифрует пароль,\nформирует токен & aes_key,\nотдает токен & aes_key
Сервер -> Клиент: токен & aes_key
Клиент -> Клиент: Сохраняет в SecureStorage aes_key
note right: Какое то время спустя: Срок жизни токена истек
Клиент -> Сервер: aes_key + пароль
note left: Хочет обновить токен
Сервер -> Сервер: Обновляет токен
Сервер -> Клиент: Отдает новый токен & aes_key

@enduml