// // Mocks generated by Mockito 5.4.4 from annotations
// // in password_manager_frontend/test/login_test.dart.
// // Do not manually edit this file.
//
// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i5;
// import 'dart:ui' as _i7;
//
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:password_manager_frontend/models/account.dart' as _i2;
// import 'package:password_manager_frontend/models/user.dart' as _i3;
// import 'package:password_manager_frontend/services/account_service.dart' as _i8;
// import 'package:password_manager_frontend/services/auth_service.dart' as _i6;
// import 'package:password_manager_frontend/services/login_service.dart' as _i4;
// import 'package:password_manager_frontend/services/user_service.dart' as _i9;
//
//
//
// class _FakeUri_0 extends _i1.SmartFake implements Uri {
//   _FakeUri_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }
//
// class _FakeAccount_1 extends _i1.SmartFake implements _i2.Account {
//   _FakeAccount_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }
//
// class _FakeUser_2 extends _i1.SmartFake implements _i3.User {
//   _FakeUser_2(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }
//
// /// A class which mocks [LoginService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockLoginService extends _i1.Mock implements _i4.LoginService {
//   MockLoginService() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i5.Future<Map<String, dynamic>> login({
//     required String? accountLogin,
//     required String? password,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #login,
//           [],
//           {
//             #accountLogin: accountLogin,
//             #password: password,
//           },
//         ),
//         returnValue:
//             _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
//       ) as _i5.Future<Map<String, dynamic>>);
//
//   @override
//   Uri buildUri(String? endpoint) => (super.noSuchMethod(
//         Invocation.method(
//           #buildUri,
//           [endpoint],
//         ),
//         returnValue: _FakeUri_0(
//           this,
//           Invocation.method(
//             #buildUri,
//             [endpoint],
//           ),
//         ),
//       ) as Uri);
//
//   @override
//   _i5.Future<dynamic> get(String? endpoint) => (super.noSuchMethod(
//         Invocation.method(
//           #get,
//           [endpoint],
//         ),
//         returnValue: _i5.Future<dynamic>.value(),
//       ) as _i5.Future<dynamic>);
//
//   @override
//   _i5.Future<dynamic> post(
//     String? endpoint,
//     Map<String, dynamic>? body,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #post,
//           [
//             endpoint,
//             body,
//           ],
//         ),
//         returnValue: _i5.Future<dynamic>.value(),
//       ) as _i5.Future<dynamic>);
// }
//
// /// A class which mocks [AuthService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockAuthService extends _i1.Mock implements _i6.AuthService {
//   MockAuthService() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   int get accountId => (super.noSuchMethod(
//         Invocation.getter(#accountId),
//         returnValue: 0,
//       ) as int);
//
//   @override
//   int get userId => (super.noSuchMethod(
//         Invocation.getter(#userId),
//         returnValue: 0,
//       ) as int);
//
//   @override
//   int get categoryId => (super.noSuchMethod(
//         Invocation.getter(#categoryId),
//         returnValue: 0,
//       ) as int);
//
//   @override
//   bool get isLoggedIn => (super.noSuchMethod(
//         Invocation.getter(#isLoggedIn),
//         returnValue: false,
//       ) as bool);
//
//   @override
//   bool get hasListeners => (super.noSuchMethod(
//         Invocation.getter(#hasListeners),
//         returnValue: false,
//       ) as bool);
//
//   @override
//   void setCategoryId(int? id) => super.noSuchMethod(
//         Invocation.method(
//           #setCategoryId,
//           [id],
//         ),
//         returnValueForMissingStub: null,
//       );
//
//   @override
//   _i5.Future<void> setSessionFromToken({
//     required int? accountId,
//     required int? userId,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #setSession,
//           [],
//           {
//             #accountId: accountId,
//             #userId: userId,
//           },
//         ),
//         returnValue: _i5.Future<void>.value(),
//         returnValueForMissingStub: _i5.Future<void>.value(),
//       ) as _i5.Future<void>);
//
//   @override
//   void clearSession() => super.noSuchMethod(
//         Invocation.method(
//           #clearSession,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );
//
//   @override
//   _i5.Future<void> logout() => (super.noSuchMethod(
//         Invocation.method(
//           #logout,
//           [],
//         ),
//         returnValue: _i5.Future<void>.value(),
//         returnValueForMissingStub: _i5.Future<void>.value(),
//       ) as _i5.Future<void>);
//
//   @override
//   void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
//         Invocation.method(
//           #addListener,
//           [listener],
//         ),
//         returnValueForMissingStub: null,
//       );
//
//   @override
//   void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
//         Invocation.method(
//           #removeListener,
//           [listener],
//         ),
//         returnValueForMissingStub: null,
//       );
//
//   @override
//   void dispose() => super.noSuchMethod(
//         Invocation.method(
//           #dispose,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );
//
//   @override
//   void notifyListeners() => super.noSuchMethod(
//         Invocation.method(
//           #notifyListeners,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );
// }
//
// /// A class which mocks [AccountService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockAccountService extends _i1.Mock implements _i8.AccountService {
//   MockAccountService() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i5.Future<_i2.Account> fetchAccountById(int? id) => (super.noSuchMethod(
//         Invocation.method(
//           #fetchAccountById,
//           [id],
//         ),
//         returnValue: _i5.Future<_i2.Account>.value(_FakeAccount_1(
//           this,
//           Invocation.method(
//             #fetchAccountById,
//             [id],
//           ),
//         )),
//       ) as _i5.Future<_i2.Account>);
//
//   @override
//   Uri buildUri(String? endpoint) => (super.noSuchMethod(
//         Invocation.method(
//           #buildUri,
//           [endpoint],
//         ),
//         returnValue: _FakeUri_0(
//           this,
//           Invocation.method(
//             #buildUri,
//             [endpoint],
//           ),
//         ),
//       ) as Uri);
//
//   @override
//   _i5.Future<dynamic> get(String? endpoint) => (super.noSuchMethod(
//         Invocation.method(
//           #get,
//           [endpoint],
//         ),
//         returnValue: _i5.Future<dynamic>.value(),
//       ) as _i5.Future<dynamic>);
//
//   @override
//   _i5.Future<dynamic> post(
//     String? endpoint,
//     Map<String, dynamic>? body,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #post,
//           [
//             endpoint,
//             body,
//           ],
//         ),
//         returnValue: _i5.Future<dynamic>.value(),
//       ) as _i5.Future<dynamic>);
// }
//
// /// A class which mocks [UserService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockUserService extends _i1.Mock implements _i9.UserService {
//   MockUserService() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i5.Future<_i3.User> fetchUserById(int? userId) => (super.noSuchMethod(
//         Invocation.method(
//           #fetchUserById,
//           [userId],
//         ),
//         returnValue: _i5.Future<_i3.User>.value(_FakeUser_2(
//           this,
//           Invocation.method(
//             #fetchUserById,
//             [userId],
//           ),
//         )),
//       ) as _i5.Future<_i3.User>);
//
//   @override
//   Uri buildUri(String? endpoint) => (super.noSuchMethod(
//         Invocation.method(
//           #buildUri,
//           [endpoint],
//         ),
//         returnValue: _FakeUri_0(
//           this,
//           Invocation.method(
//             #buildUri,
//             [endpoint],
//           ),
//         ),
//       ) as Uri);
//
//   @override
//   _i5.Future<dynamic> get(String? endpoint) => (super.noSuchMethod(
//         Invocation.method(
//           #get,
//           [endpoint],
//         ),
//         returnValue: _i5.Future<dynamic>.value(),
//       ) as _i5.Future<dynamic>);
//
//   @override
//   _i5.Future<dynamic> post(
//     String? endpoint,
//     Map<String, dynamic>? body,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #post,
//           [
//             endpoint,
//             body,
//           ],
//         ),
//         returnValue: _i5.Future<dynamic>.value(),
//       ) as _i5.Future<dynamic>);
// }
