name: hashing_utility_package
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
#  sdk: '^3.5.3'
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  pointycastle: ^3.4.0  # Add this for PBKDF2 support
  http: ^1.2.2
  crypto: ^3.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
